apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployments-sa
  namespace: kube-custom
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployments-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployments-binding
subjects:
  - kind: ServiceAccount
    name: deployments-sa
    namespace: kube-custom
roleRef:
  kind: ClusterRole
  name: deployments-role
  apiGroup: rbac.authorization.k8s.io
